### PR TITLE
Fix set button colors on the dialog

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**
Setting color after showing the dailog does not seem to work on multiple devices

Devices tested on:
Xiaomi Redmi Note 5 Pro running Android 11
Samsung Galaxy S20 Running Android 10

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Rest of the formatting changes are due to running ktlint included in the project

**Comment by SubhrajyotiSen** [comment]
Please release a new version of the library if possible once this is merged. Another project is dependent on this fix.

**Comment by Dhaval2404** [comment]
@SubhrajyotiSen Everythings looks good. I will try to release the new version over the weekend. 

Thank you so much for your contribution!

**Comment by SubhrajyotiSen** [comment]
Hi, can this be merged?

**Comment by Dhaval2404** [comment]
@SubhrajyotiSen Ohh So Sorry! I almost forgot this. Thanks for the reminder. I will do it by EOD. 

Thank you.

**Comment by Dhaval2404** [comment]
@SubhrajyotiSen It seems like setting a color before showing a dialog not working in a stock ROM 😢.

I have verified the same in the following devices:
-  Xiaomi MI A2 (Android 10)
-  Pixel 3a (Android 10 - Emulator)

Can you please verify the same if possible? 

Tomorrow, I will check on Redmi Note 5 Pro to find any alternate solution.

**Comment by SubhrajyotiSen** [comment]
I will take a look at this tomorrow and try getting a solution that works universally

**Comment by SubhrajyotiSen** [comment]
Hey. I tried my changes on a Pixel XL (Android 10) Emulator. The color seems to work

**Pull request closed without merging**
